##
# Production Dockerfile
#

##
# STAGE 1
# build environment
#
FROM node:12.9.1-alpine as node

WORKDIR /app
COPY . /app

RUN yarn install --pure-lockfile
RUN yarn react-scripts build


##
# STAGE 2
# production environment
#
FROM nginx:1.17.4-alpine as nginx
COPY --from=node /app/build /usr/share/nginx/html
