##
# Development Dockerfile
#

##
# STAGE 1
# build
#
FROM node:12.9.1-alpine as node
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . /app
# COPY package.json yarn.lock /app/
RUN yarn install --pure-lockfile
