##
# Production Dockerfile
#

##
# STAGE 1
# build
#
FROM node:12.9.1-alpine as node
WORKDIR /app
COPY . /app
# COPY package.json package.json /app/
RUN yarn install --pure-lockfile

RUN yarn react-scripts build


##
# STAGE 2
# serve
#
FROM nginx:1.17.4-alpine as nginx
COPY --from=node /app/build /usr/share/nginx/html
