version: 2
jobs:
  test:
    docker:
      # - image: circleci/classic
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            # docker network create web_local
            docker-compose up dev
            docker-compose run --rm test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP: "create-react-app-docker"
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master

workflows:
  version: 2
  setup_and_run:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
                - /^deploy/
          requires:
            - ci
